# Generated by Django 4.2.3 on 2023-07-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0004_delete_guest"),
        ("guest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="invitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invitation.invitation",
            ),
        ),
    ]
