# Generated by Django 4.2.3 on 2023-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0002_alter_guest_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="guest_profiles/"),
        ),
    ]
