# Generated by Django 4.2.3 on 2023-08-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0003_guest_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="invitation",
        ),
    ]
