# Generated by Django 4.2.3 on 2023-08-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0006_remove_invitation_guest"),
        ("guest", "0004_remove_guest_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="invitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invitation.invitation",
            ),
        ),
    ]
