# Generated by Django 4.2.3 on 2023-07-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="file_upload",
            field=models.FileField(null=True, upload_to="files/"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="img_upload",
            field=models.ImageField(null=True, upload_to="img/"),
        ),
    ]
