# Generated by Django 4.2.3 on 2023-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0002_invitation_file_upload_invitation_img_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="file_upload",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="img_upload",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
