# Generated by Django 4.2.3 on 2023-07-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0003_remove_invitation_file_upload_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Guest",
        ),
    ]
