# Generated by Django 4.2.3 on 2023-08-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0004_remove_guest_invitation"),
        ("invitation", "0004_delete_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="guest",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="guest.guest"
            ),
        ),
    ]
